WSO2 EI Microsoft Azure connector.
wso2-extensions/esb-connector-msazurestorage pull request #1
Opened 2018-01-26 06:04 UTC by kesavany

## Purpose
WSO2 EI Connector for Microsoft Azure Storage.

## Goals
The initial version of Microsoft Azure Storage connector.

## Approach
N/A

## User stories
N/A

## Release note
N/A

## Documentation
Git Doc added

## Training
N/A

## Certification
N/A

## Marketing
N/A

## Automation tests
 - Unit tests 
   > N/A
 - Integration tests
   > Added.

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

## Samples
N/A

## Related PRs
N/A

## Migrations (if applicable)
N/A

## Test environment
Maven 3.x
Java 1.8
Platform:
UBUNTU 16.04
WSO2 EI 6.1.1
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2018-02-02 03:15 UTC, dimslee requested changes

2018-02-02 03:15 UTC, muthulee commented on src/test/java/org/wso2/carbon/connector/integration/test/msazurestorage/MsAzureStorageConnectorIntegrationTest.java
> +        Assert.assertTrue(containersFromEi.contains(connectorProperties.getProperty("containerName")));
Need to assertEqual the name of the container.

2018-02-06 06:17 UTC, keerthu approved these changes

2018-02-06 06:20 UTC, dimslee approved these changes

2018-02-06 06:33 UTC, merged